### ISSUE TITLE
consider allowing users to pause the animated background

### ISSUE THREAD

**Issue by chaserx** [bluegrass-devs/bluegrass-devs.github.io#21]
I find motion in animations like that used in the background will sometimes set off my motion sickness. 

IMHO, it would be good if we gave the user an option to stop the animation so that it's easier to interact with the site.

I found an example codepen that does just that. Seems easy enough to add a class via javascript. 
https://codepen.io/zjun/pen/dGPqzQ

**Comment by chaserx** [comment]
If I can find some time, I might propose this change.

**Comment by joeblankenship1** [comment]
First and foremost, thank you very much for letting me know this.
I think instead of pausing the animated gif, I just transition to a nice, high DPI graphic for the background image. That will make it safer and more enjoyable for everyone.
The last thing I want is to inadvertently hurt anyone.

**Comment by joeblankenship1** [comment]
I resolved this issue with [PR 22](https://github.com/bluegrass-devs/bluegrass-devs.github.io/pull/22). Let me know if we need to re-open this for additional modification.

**Comment by chaserx** [comment]
Thanks @joeblankenship1
