### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by summasmiff** [bluegrass-devs/bluegrass-devs.github.io#32]
SSL certificate expired 6 days ago (June 22, 2020). Chrome won't let certain pages be accessed: `https://www.bluegrassdevs.org/rss/bdg_rss.xml` among others.

**Comment by joekr** [comment]
well without the `www` it worked 
![image](https://user-images.githubusercontent.com/132980/86858181-2bbe4400-c08e-11ea-9317-381592d7461b.png)

**Comment by joekr** [comment]
But adding back in the `www` breaks it.
![image](https://user-images.githubusercontent.com/132980/86858262-50b2b700-c08e-11ea-9e08-51595a9a5021.png)

**Comment by joekr** [comment]
Based on this https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site the DNS looks correct to me (and hasn't changed)

![image](https://user-images.githubusercontent.com/132980/86858629-07af3280-c08f-11ea-9e0e-f0998c3261aa.png)

**Comment by joekr** [comment]
I've reached out to github support as well. I'm at a loss as to why the cert won't renew for www.bluegrassdevs.org.

**Comment by joekr** [comment]
After hearing back from github it turns out I needed the CNAME

![image](https://user-images.githubusercontent.com/132980/86867388-bc9e1b00-c0a0-11ea-8bf2-7342be435f3c.png)


![image](https://user-images.githubusercontent.com/132980/86867345-aee89580-c0a0-11ea-89d3-d58e23fa75ea.png)

Now we wait ....

**Comment by joekr** [comment]
@summasmiff 
![image](https://user-images.githubusercontent.com/132980/86867704-4a7a0600-c0a1-11ea-8d85-a1dcdba27f0b.png)
